### PR TITLE
Fixes conflict with NamedTuples on case insensitive filesystems.

### PR DESCRIPTION
**Pull request by dm3**
Tested on the default Windows case-insensitive file system, Julia 0.6.4, DataStreams 0.3.7. 

If the `NamedTuples/src` is placed on `Base.LOAD_PATH` after `DataStreams/src`, Julia (at least 0.6.x) tries to load the module from `DataStreams/src/namedtuples.jl`, unsuccessfully. 

To reproduce run:

```julia
empty!(Base.LOAD_PATH)
base = joinpath(Pkg.Dir._pkgroot(), "v0.6")
push!(Base.LOAD_PATH, joinpath(base, "Compat", "src"))
push!(Base.LOAD_PATH, joinpath(base, "Missings", "src"))
push!(Base.LOAD_PATH, joinpath(base, "WeakRefStrings", "src"))
push!(Base.LOAD_PATH, joinpath(base, "DataStreams", "src"))
push!(Base.LOAD_PATH, joinpath(base, "NamedTuples", "src"))
ENV["JULIA_PKGDIR"] = "does-not-exist"

using DataStreams
```
results in
```
$ julia --compilecache=no run.jl
ERROR: LoadError: LoadError: LoadError: UndefVarError: NamedTuple not defined
Stacktrace:
 [1] include_from_node1(::String) at .\loading.jl:576
 [2] eval(::Module, ::Any) at .\boot.jl:235
 [3] _require(::Symbol) at .\loading.jl:490
 [4] require(::Symbol) at .\loading.jl:405
 [5] include_from_node1(::String) at .\loading.jl:576
while loading C:\Users\dm3\.julia\v0.6\DataStreams\src\NamedTuples.jl, in expression starting on line 521
while loading C:\Users\dm3\.julia\v0.6\DataStreams\src\DataStreams.jl, in expression starting on line 487
```

Moving the `NamedTuples` before the `DataStreams` in the `LOAD_PATH` sequence fixes the error.

### CODE REVIEW

**Comment by dm3** [comment]
This PR applies to the 0.6* release branch. Is it possible to release a 0.3.8 DataStreams with this applied for people who can't migrate to Julia 0.7+ yet? I've submitted #93 which applies to the master.

**Comment by quinnj** [comment]
Can I ask why you're doing
```julia
push!(Base.LOAD_PATH, joinpath(base, "Compat", "src"))
push!(Base.LOAD_PATH, joinpath(base, "Missings", "src"))
push!(Base.LOAD_PATH, joinpath(base, "WeakRefStrings", "src"))
push!(Base.LOAD_PATH, joinpath(base, "DataStreams", "src"))
push!(Base.LOAD_PATH, joinpath(base, "NamedTuples", "src"))
```
? That seems like a pretty bad way to hack the package manager into finding those packages.

**Comment by quinnj** [comment]
I don't really have any plans to do any further releases for 0.6, so it would be hard to figure out how to go back and find the right commit of the last 0.6 release and then we'd have to do a branch w/ this commit off that. If we can solve your path hacking problem instead, that seems like it would be easier.

**Comment by dm3** [comment]
> Can I ask why you're doing
> 
> ```julia
> push!(Base.LOAD_PATH, joinpath(base, "Compat", "src"))
> push!(Base.LOAD_PATH, joinpath(base, "Missings", "src"))
> push!(Base.LOAD_PATH, joinpath(base, "WeakRefStrings", "src"))
> push!(Base.LOAD_PATH, joinpath(base, "DataStreams", "src"))
> push!(Base.LOAD_PATH, joinpath(base, "NamedTuples", "src"))
> ```
> 
> ? That seems like a pretty bad way to hack the package manager into finding those packages.

I'm doing this in order to construct a "clean" environment for my project. The paths are then copied out and packaged together with my code to make a self-contained release.

**Comment by quinnj** [comment]
Fixed via e3114aabd50f17c59ef324eb6af4ca1e4722cb2b

**Pull request closed without merging**
